export default function Head() {
  return (
    <>
      <title>Jikmunn Metaverse</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta
        name="description"
        content="Generated by create next app and developed by Muhammad Azizul Hoque Jiku"
      />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
